Repository apoclyps/my-dev-space, pull requests merged in 2018-10, with the labels that each got.

#400 Removal of .DS_Store & update to .gitignore
  .gitignore
  services/.DS_Store
Labels: Type: Cleanup, hacktoberfest

#407 Various design changes; sticky menu and footer, background color, res…
  services/client/src/App.js
  services/client/src/components/event-separator/styles.js
  services/client/src/components/footer/styles.js
  services/client/src/components/header/styles/index.js
  services/client/src/components/header/styles/navigation.js
  services/client/src/components/spinner/styles/index.js
Labels: CSS, design, hacktoberfest

#408 Adding additional formatted date for events
  services/client/src/components/event/time-to-event.js
Labels: Events, enhancement, hacktoberfest

#410 Fix incorrect command in README.md
  README.md
Labels: documentation, hacktoberfest

#409 Pre commit hook
  .huskyrc
  package.json
  pre-commit-tests.sh
Labels: hacktoberfest

#418 Implement reducer tests for `events` #397
  services/client/src/pages/events/action-creators/tests/index.spec.js
Labels: hacktoberfest

#422 Pagination for events service
  services/events/project/api/events.py
Labels: hacktoberfest

#423 Scripts Readme Typo fix
  scripts/README.md
Labels: documentation, hacktoberfest

#429 Add videos API to swagger docs
  services/swagger/swagger.json
Labels: documentation, hacktoberfest

#432 Implement selector tests for events #398
  services/client/src/pages/events/action-creators/tests/index.spec.js
Labels: hacktoberfest, react, redux, tests

#433 Adding link to API docs in the Footer component
  services/client/src/components/footer/index.js
  services/swagger/swagger.json
Labels: CSS, documentation

#434 Add lambda to pull data from Farset Labs calendar
  lambdas/README.md
  lambdas/eventbrite/package.json
  lambdas/farsetlabs/.gitignore
  lambdas/farsetlabs/config.js
  lambdas/farsetlabs/handler.js
  lambdas/farsetlabs/package-lock.json
  lambdas/farsetlabs/package.json
  lambdas/farsetlabs/serverless.yml
  lambdas/package.json
Labels: hacktoberfest, lambda

#435 Replace pre-commit hook with a pre-push hook
  .huskyrc
  PULL_REQUEST_TEMPLATE.md
  docker-compose-dev.yml
  docker-compose-prod.yml
  docker-compose-stage.yml
  package-lock.json
  pre-push-tests.sh
  services/events/pytest.ini
  services/users/pytest.ini
Labels: Type: Cleanup, documentation, hacktoberfest, tests

#442 Amending events service to filter deleted events
  scripts/src/eventbrite_events.py
  scripts/src/meetup_events.py
  scripts/src/northern_ireland_science_festival_events.py
  services/events/migrations/env.py
  services/events/project/api/events.py
Labels: Type: Cleanup, flask, python

#447 Restructure current producer lambdas in preparation for transformers
  lambdas/README.md
  lambdas/eventbrite/handler.js
  lambdas/eventbrite/serverless.yml
  lambdas/farsetlabs/handler.js
  lambdas/farsetlabs/serverless.yml
  lambdas/meetupcom/handler.js
  lambdas/meetupcom/serverless.yml
  lambdas/package.json
Labels: hacktoberfest, lambda

#445 Refactors .travis.yml to use build steps
  .travis.yml
Labels: Build, hacktoberfest

#448 Add initial setup for farset labs event transformer
  lambdas/README.md
  lambdas/farsetlabs/handlers/producer.js
  lambdas/farsetlabs/handlers/transformer.js
  lambdas/farsetlabs/serverless.yml
  lambdas/package.json
Labels: hacktoberfest, lambda

#459 Update to using Farset Labs Calendar JSON endpoint
  lambdas/README.md
  lambdas/farsetlabs/config.js
  lambdas/farsetlabs/handlers/producer.js
  lambdas/farsetlabs/handlers/transformer.js
  lambdas/farsetlabs/package-lock.json
  lambdas/farsetlabs/package.json
  lambdas/farsetlabs/serverless.yml
Labels: hacktoberfest, lambda

#460 Implement Farset Labs events transformer
  lambdas/farsetlabs/config.js
  lambdas/farsetlabs/handlers/producer.js
  lambdas/farsetlabs/handlers/schemas/event-schema.json
  lambdas/farsetlabs/handlers/transformer.js
  lambdas/farsetlabs/package-lock.json
  lambdas/farsetlabs/package.json
  lambdas/farsetlabs/serverless.yml
  lambdas/farsetlabs/utils.js
Labels: hacktoberfest, lambda

#463 Update meetupcom lambda in preparation for transformer implementation
  lambdas/meetupcom/config.js
  lambdas/meetupcom/handlers/producer.js
  lambdas/meetupcom/package-lock.json
  lambdas/meetupcom/package.json
  lambdas/meetupcom/serverless.yml
  lambdas/meetupcom/utils.js
Labels: hacktoberfest, lambda

#465 Update Farset Labs calendar lambda for fixes and readme updates
  lambdas/README.md
  lambdas/farsetlabs/handlers/producer.js
  lambdas/farsetlabs/handlers/transformer.js
Labels: hacktoberfest, lambda

#466 Fix for caching event requests with url parameters
  services/events/project/api/events.py
Labels: bug

#479 Adding css background color to Events spinner
  services/client/src/App.js
Labels: CSS

#480 Implements developer listings on Muxer
  scripts/.env.example
  scripts/Pipfile
  scripts/Pipfile.lock
  scripts/README.md
  scripts/src/github_users.py
  services/client/src/App.js
  services/client/src/components/developer/blog.js
  services/client/src/components/developer/company.js
  services/client/src/components/developer/content.js
  services/client/src/components/developer/github.js
  services/client/src/components/developer/index.js
  services/client/src/components/developer/styles/content.js
  services/client/src/components/developer/styles/index.js
  services/client/src/components/header/navigation.js
  services/client/src/pages/developers/index.js
  services/client/src/utils/format.js
  services/events/migrations/README
  services/events/migrations/versions/23ee9e7d008e_.py
  services/events/migrations/versions/5da14a4e4c7a_.py
  services/events/project/__init__.py
  services/events/project/api/developers.py
  services/events/project/api/models.py
  services/events/project/tests/test_developer_model.py
  services/events/project/tests/utils.py
  services/nginx/flask.conf
Labels: CSS, HTML, Special Deployment Handling, hacktoberfest, javascript, python, react

#488 bugfix: Remove out of range exception in northern_ireland_science_festival_events.py
  scripts/src/northern_ireland_science_festival_events.py
Labels: bug, hacktoberfest, python

#487 Adds a location parameter to the Events endpoint
  scripts/src/eventbrite_events.py
  scripts/src/farset_events.py
  scripts/src/meetup_events.py
  services/events/migrations/versions/dccf9917623a_.py
  services/events/project/api/events.py
  services/events/project/api/models.py
  services/events/project/tests/test_event_model.py
  services/events/project/tests/utils.py
Labels: Special Deployment Handling, flask, python

#490 Update lambdas for linting and include in test run
  docker-compose-dev.yml
  docker-compose-prod.yml
  docker-compose-stage.yml
  lambdas/Dockerfile-test
  lambdas/eventbrite/config.js
  lambdas/eventbrite/handlers/producer.js
  lambdas/eventbrite/handlers/transformer.js
  lambdas/eventbrite/package.json
  lambdas/eventbrite/utils.js
  lambdas/farsetlabs/config.js
  lambdas/farsetlabs/handlers/producer.js
  lambdas/farsetlabs/handlers/transformer.js
  lambdas/farsetlabs/package.json
  lambdas/farsetlabs/utils.js
  lambdas/meetupcom/config.js
  lambdas/meetupcom/handlers/transformer.js
  lambdas/meetupcom/package.json
  lambdas/meetupcom/utils.js
  lambdas/package-lock.json
  lambdas/package.json
  package-lock.json
  test.sh
Labels: hacktoberfest, lambda, linting

#498 Disabling the developer feature
  services/client/src/components/header/navigation.js
Labels: Type: Cleanup

#500 Updating documentation and makefile help
  Makefile
  README.md
  docs/docker-readme.md
Labels: Shell Script, Type: Cleanup, documentation

#504 refactor: Use list comprehension instead of for loops
  services/events/project/api/events.py
  services/events/project/api/speakers.py
  services/events/project/api/videos.py
Labels: Type: Cleanup, hacktoberfest, python

#506 Refactor/assert equal instead of assert true
  services/events/project/tests/test_config.py
  services/users/project/tests/test_auth.py
  services/users/project/tests/test_config.py
Labels: flask, hacktoberfest, python, tests

#509 Update itsdangerous to 1.1.0
  services/events/Pipfile
  services/events/Pipfile.lock
  services/users/Pipfile
  services/users/Pipfile.lock
Labels: bug, dependencies, hacktoberfest

#511 Tests for Eventbrite transformer lambda
  lambdas/tests/eventbrite/handlers/__snapshots__/tranformer.test.js.snap
  lambdas/tests/eventbrite/handlers/test-data/events-payload-empty.json
  lambdas/tests/eventbrite/handlers/test-data/events-payload-incomplete.json
  lambdas/tests/eventbrite/handlers/test-data/events-payload-invalid.json
  lambdas/tests/eventbrite/handlers/test-data/events-payload-populated.json
  lambdas/tests/eventbrite/handlers/tranformer.test.js
Labels: hacktoberfest, lambda, tests

#507 Update lambdas for testing and include in test run
  lambdas/.eslintrc
  lambdas/Dockerfile-test
  lambdas/eventbrite/handlers/producer.js
  lambdas/eventbrite/handlers/transformer.js
  lambdas/farsetlabs/handlers/transformer.js
  lambdas/meetupcom/handlers/transformer.js
  lambdas/package-lock.json
  lambdas/package.json
  lambdas/tests/eventbrite/handlers/__snapshots__/tranformer.test.js.snap
  lambdas/tests/eventbrite/handlers/producer.test.js
  lambdas/tests/eventbrite/handlers/test-data/events-payload-empty.json
  lambdas/tests/eventbrite/handlers/test-data/events-payload-incomplete.json
  lambdas/tests/eventbrite/handlers/test-data/events-payload-invalid.json
  lambdas/tests/eventbrite/handlers/test-data/events-payload-populated.json
  lambdas/tests/eventbrite/handlers/tranformer.test.js
  lambdas/tests/eventbrite/test-utils.js
  lambdas/tests/farsetlabs/handlers/producer.test.js
  lambdas/tests/farsetlabs/handlers/tranformer.test.js
  lambdas/tests/meetupcom/handlers/producer.test.js
  lambdas/tests/meetupcom/handlers/tranformer.test.js
  test.sh
Labels: hacktoberfest, lambda, tests
