Repository apoclyps/my-dev-space, pull requests merged in 2018-06, with the labels that each got.

#130 Adding additional fields to events endpoint
  services/events/manage.py
  services/events/project/api/events.py
  services/events/project/api/models.py
  services/events/project/tests/test_event_model.py
  services/events/project/tests/utils.py
Labels: Python, SQL

#134 [UI] Adding staging/production deploy
  services/client/Dockerfile-dev
  services/client/Dockerfile-prod
  services/client/Dockerfile-stage
  services/client/package.json
  services/client/src/components/Content.js
Labels: Build

#135 [config] Events env config
  .travis.yml
  docker-compose-dev.yml
  docker-compose-prod.yml
  docker-compose-stage.yml
  docker-push.sh
  services/client/Dockerfile-stage
  test.sh
Labels: Build

#136 [ui-client] Adding env config for Client
  docker-push.sh
  services/client/.env
  services/client/src/pages/Events.js
Labels: Build

#143 Removing unused gh-pages dependency and deploy task
  services/client/package-lock.json
  services/client/package.json
  services/client/yarn.lock
Labels: Type: Cleanup, dependencies

#144 Bumping react-scripts to 1.1.4
  services/client/Dockerfile-dev
  services/client/Dockerfile-prod
  services/client/Dockerfile-stage
  services/client/package-lock.json
  services/client/package.json
Labels: Build, dependencies

#147 Formatting client using prettier
  services/client/package.json
  services/client/src/App.js
  services/client/src/App.test.js
  services/client/src/components/CallToActionBanner.js
  services/client/src/components/Content.js
  services/client/src/components/Footer.js
  services/client/src/components/Header.js
  services/client/src/components/Pagination.js
  services/client/src/index.js
  services/client/src/pages/Developers.js
  services/client/src/pages/Events.js
  services/client/src/pages/Latest.js
  services/client/src/pages/Projects.js
  services/client/src/pages/Speakers.js
  services/client/src/registerServiceWorker.js
Labels: JavaScript, Type: Cleanup

#149 Adds scripts to retrieve data from Eventbrite & Meetup
  scripts/.env
  scripts/Pipfile
  scripts/src/eventbrite.py
  scripts/src/meetup.py
Labels: Linting, dependencies

#150 Improving the consistency of datetime handling for created and time events
  scripts/.env.example
  scripts/Pipfile
  scripts/src/eventbrite_events.py
  scripts/src/meetup.py
  services/events/project/api/events.py
  services/events/project/api/models.py
  services/events/project/tests/test_event_model.py
Labels: Python, Type: Cleanup

#152 Adding event source to scripts and service
  scripts/Pipfile
  scripts/src/eventbrite_events.py
  scripts/src/meetup_events.py
  services/events/manage.py
  services/events/project/api/events.py
  services/events/project/api/models.py
  services/events/project/tests/test_event_model.py
  services/events/project/tests/utils.py
Labels: Python

#153 Python formatting using Black
  services/events/manage.py
  services/events/project/__init__.py
  services/events/project/api/events.py
  services/events/project/api/models.py
  services/events/project/config.py
  services/events/project/tests/base.py
  services/events/project/tests/test_config.py
  services/events/project/tests/test_event_model.py
  services/events/project/tests/utils.py
  services/users/manage.py
  services/users/migrations/env.py
  services/users/migrations/versions/98de388d3262_.py
  services/users/migrations/versions/f127120d3cb8_.py
  services/users/project/__init__.py
  services/users/project/api/auth.py
  services/users/project/api/models.py
  services/users/project/api/users.py
  services/users/project/api/utils.py
  services/users/project/config.py
  services/users/project/tests/base.py
  services/users/project/tests/test_auth.py
  services/users/project/tests/test_config.py
  services/users/project/tests/test_user_model.py
  services/users/project/tests/test_users.py
Labels: Linting, Python

#156 Adding sorting and source logos to content events
  services/client/src/components/Content.js
  services/client/src/components/Header.js
  services/client/src/pages/Events.js
Labels: JavaScript

#163 [events-service] Adding some minor cleanup for events
  services/client/src/components/Content.js
  services/events/project/tests/test_event_model.py
  services/users/manage.py
Labels: Type: Cleanup

#160 [events-service] Adding filter to events query to remove past events
  services/events/project/api/events.py
Labels: Python, SQL

#164 [services] Adding python black formatter as a project dependency
  services/events/manage.py
  services/events/requirements.txt
  services/users/manage.py
  services/users/requirements.txt
Labels: Python, Type: Cleanup, dependencies

#169 [client] General refactoring pass for client
  e2e/login.test.js
  e2e/message.test.js
  e2e/register.test.js
  e2e/status.test.js
  services/client/package.json
  services/client/src/App.js
  services/client/src/components/Content.js
  services/client/src/components/Header.js
  services/client/src/pages/Developers.js
  services/client/src/pages/Projects.js
  services/client/src/pages/Speakers.js
Labels: JavaScript, Linting, Type: Cleanup

#171 [client] Updating client dependencies
  services/client/package.json
  services/client/yarn.lock
Labels: JavaScript, dependencies

#172 [e2e testing] Updating e2e tests to provide a valid basic example and updates test …
  e2e/index.test.js
  services/client/src/App.test.js
  services/events/.flake8
  services/users/.flake8
  test.sh
Labels: Build, JavaScript, Testing

#175 Adding Northern Ireland Science Festival events
  scripts/Pipfile
  scripts/src/northern_ireland_science_festical_events.py
  services/client/src/components/Content.js
  services/events/project/api/models.py
  services/events/project/tests/test_event_model.py
Labels: Event Stream, Python

#184 [ui-client] Updating navigation bar and events name to titlecase
  e2e/index.test.js
  services/client/src/App.js
  services/client/src/components/Content.js
  services/client/src/components/Footer.js
  services/client/src/components/Header.js
  services/client/src/components/Pagination.js
  services/client/src/pages/Events.js
  services/client/src/pages/Latest.js
Labels: JavaScript, Type: Cleanup

#185 [client] Refactoring css, updating favicon, and manifest name
  services/client/public/favicon.ico
  services/client/public/index.html
  services/client/public/manifest.json
  services/client/src/App.css
  services/client/src/components/CallToActionBanner.js
  services/client/src/components/Content.js
  services/client/src/components/Header.js
  services/client/src/index.css
  services/client/src/index.js
Labels: CSS, JavaScript, Type: Cleanup

#199 Update for getting started
  README.md
  services/client/.npmrc
  services/client/Dockerfile-dev
  services/client/package-lock.json
  services/client/yarn.lock
  services/events/manage.py
Labels: Type: Cleanup

#201 Adding new relic APM for events service
  docker-compose-dev.yml
  docker-compose-prod.yml
  docker-compose-stage.yml
  docker-push.sh
  ecs/ecs_events_prod_taskdefinition.json
  ecs/ecs_events_stage_taskdefinition.json
  services/client/Dockerfile-dev
  services/events/Dockerfile-dev
  services/events/Dockerfile-prod
  services/events/Dockerfile-stage
  services/events/entrypoint-stage.sh
  services/events/entrypoint.sh
  services/events/newrelic.ini
  services/events/requirements.txt
Labels: Monitoring

#203 Bumping python docker image from 3.6.3 to 3.6.6
  services/events/Dockerfile-dev
  services/events/Dockerfile-prod
  services/events/Dockerfile-stage
  services/users/Dockerfile-dev
  services/users/Dockerfile-prod
  services/users/Dockerfile-stage
Labels: Docker, Python, dependencies
