Repository apoclyps/my-dev-space, pull requests merged in 2018-08, with the labels that each got.

#293 Adding fix for psycopg2 warning
  services/events/Pipfile
  services/events/Pipfile.lock
  services/users/Pipfile
  services/users/Pipfile.lock
Labels: Docker, bug

#294 Adding ipython to services
  Pipfile.lock
  README.md
  services/events/Pipfile
  services/events/Pipfile.lock
  services/events/manage.py
  services/users/Pipfile
  services/users/Pipfile.lock
  services/users/manage.py
Labels: Build, Python

#297 Adding events script and icon for farset labs events
  .env
  scripts/load_data.sh
  scripts/src/farset_events.py
  services/client/src/components/event/icon.js
Labels: Event Stream, JavaScript, Python, Shell Script

#301 event service response limit
  services/events/project/api/events.py
Labels: Performance, Python

#311 Fix for react production client build to use multi-stage build
  services/client/Dockerfile-prod
  services/client/conf/conf.d/default.conf
Labels: Build, Performance, Type: Cleanup

#315 Adding flask-caching to reduce load times
  services/events/Pipfile
  services/events/Pipfile.lock
  services/events/project/__init__.py
  services/events/project/api/events.py
Labels: Performance, Python

#317 Bumping react-scripts to resolve insecure url-parse
  services/client/package-lock.json
  services/client/package.json
Labels: dependencies

#320 Compress Flask application's responses with gzip
  services/events/Pipfile
  services/events/Pipfile.lock
  services/events/project/__init__.py
Labels: Performance, Python

#323 Fix linting and test run for production builds
  docker-compose-prod.yml
  services/client/src/components/event/icon.js
Labels: bug

#327 Adding code climate exclusions
  .codeclimate.yml
Labels: Coverage, Type: Cleanup

#330 Adding bug/feature issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Documentation

#324 Improving visibility of event text
  services/client/src/components/event/styles/content.js
  services/client/src/components/event/styles/index.js
  services/client/src/components/event/time-to-event.js
Labels: CSS, JavaScript

#334 Adding https production links
  docker-push.sh
  scripts/load_data.sh
Labels: Security

#341 Removing red border on recent events
  services/client/src/components/event/styles/index.js
Labels: CSS
