Repository apoclyps/my-dev-space, pull requests merged in 2018-07, with the labels that each got.

#205 Set up JS linting
  services/client/.eslintignore
  services/client/.eslintrc.json
  services/client/Dockerfile-dev
  services/client/Dockerfile-prod
  services/client/Dockerfile-stage
  services/client/package-lock.json
  services/client/package.json
  services/client/src/App.js
  services/client/src/components/CallToActionBanner.js
  services/client/src/components/Content.js
  services/client/src/components/Footer.js
  services/client/src/components/Header.js
  services/client/src/pages/Events.js
  services/client/src/registerServiceWorker.js
Labels: JavaScript, Linting

#206 Python users listing
  README.md
  services/users/.flake8
  services/users/project/api/auth.py
  services/users/project/api/models.py
  services/users/project/api/users.py
  services/users/pytest.ini
  services/users/requirements.txt
  test.sh
Labels: Linting, Python

#219 Updating production DATABASE_URLs for events and users
  docker-push.sh
Labels: Build, Docker, deployment

#223 Adding configuration required for production deployments
  docker-deploy-prod.sh
  docker-deploy-stage.sh
  docker-push.sh
  ecs/ecs_events_stage_taskdefinition.json
  ecs/ecs_users_prod_taskdefinition.json
  ecs/ecs_users_stage_taskdefinition.json
Labels: Build, Docker, Infrastructure as Code, deployment

#231 Adding staging db migrations
  services/events/entrypoint-stage.sh
  services/users/entrypoint-stage.sh
Labels: SQL

#226 Adding steps to run migrations and upgrades to README
  README.md
Labels: Documentation

#233 Adding staging RDS instances for users and events
  docker-deploy-stage.sh
  docker-push.sh
  ecs/ecs_events_stage_taskdefinition.json
  ecs/ecs_users_stage_taskdefinition.json
Labels: Docker, Infrastructure as Code

#237 Adding staging fixes
  services/events/entrypoint-test.sh
  services/users/entrypoint-test.sh
Labels: bug, deployment

#236 Adding css loading spinner
  services/client/src/components/spinner/loading.js
  services/client/src/components/spinner/styles/index.js
  services/client/src/pages/events/index.js
  services/client/src/pages/videos/index.js
Labels: CSS

#240 Correcting RDS configuration for events and users services
  docker-deploy-prod.sh
  docker-deploy-stage.sh
Labels: Build, bug

#242 Updating footer and adding script to load data
  scripts/load_data.sh
  scripts/src/northern_ireland_science_festival_events.py
  services/client/src/components/footer/index.js
Labels: JavaScript

#247 Adding speakers service application code
  e2e/index.test.js
  scripts/load_data.sh
  scripts/src/speakers.py
  services/client/src/App.js
  services/client/src/components/call-to-action-banner/index.js
  services/client/src/components/header/navigation.js
  services/client/src/components/speaker/content.js
  services/client/src/components/speaker/index.js
  services/client/src/components/speaker/styles/content.js
  services/client/src/components/speaker/styles/index.js
  services/client/src/pages/index.js
  services/client/src/pages/speakers/index.js
  services/events/manage.py
  services/events/migrations/versions/5dadfc5db16d_.py
  services/events/migrations/versions/6cc236384480_.py
  services/events/project/__init__.py
  services/events/project/api/models.py
  services/events/project/api/speakers.py
  services/events/project/tests/test_speaker_model.py
  services/events/project/tests/utils.py
  services/nginx/flask.conf
Labels: CSS, Feature, JavaScript, Python

#248 Bug fixes
  .gitignore
  scripts/src/northern_ireland_science_festival_events.py
  scripts/src/speakers.py
  services/client/src/utils/get-buckets-for/index.js
  services/client/src/utils/get-buckets-for/tests/__snapshots__/index.spec.js.snap
  services/events/project/api/models.py
  test.sh
Labels: JavaScript, Python, bug

#270 Refactoring pass at scripts
  scripts/Pipfile
  scripts/Pipfile.lock
  scripts/README.md
  scripts/load_data.sh
Labels: Shell Script, Type: Cleanup

#268 Fix for user and events service failing to build in travis
  docker-push.sh
  services/events/.dockerignore
  services/users/.dockerignore
Labels: Build, Docker, bug

#253 Remodelling events database
  scripts/src/eventbrite_events.py
  scripts/src/meetup_events.py
  scripts/src/northern_ireland_science_festival_events.py
  scripts/src/speakers.py
  scripts/src/youtube_videos.py
  services/client/src/components/event/content.js
  services/client/src/components/event/index.js
  services/client/src/components/speaker/content.js
  services/client/src/components/speaker/index.js
  services/client/src/components/video/content.js
  services/client/src/components/video/index.js
  services/client/src/components/video/time-to-video.js
  services/client/src/pages/events/index.js
  services/client/src/utils/get-buckets-for/index.js
  services/client/src/utils/get-buckets-for/tests/__snapshots__/index.spec.js.snap
  services/client/src/utils/get-buckets-for/tests/test-data/events-for-every-buckets.json
  services/client/src/utils/get-buckets-for/tests/test-data/events-for-some-buckets.json
  services/events/manage.py
  services/events/migrations/versions/5da14a4e4c7a_.py
  services/events/migrations/versions/5dadfc5db16d_.py
  services/events/migrations/versions/6cc236384480_.py
  services/events/project/api/events.py
  services/events/project/api/mixins.py
  services/events/project/api/models.py
  services/events/project/api/speakers.py
  services/events/project/api/videos.py
  services/events/project/db/Dockerfile
  services/events/project/db/extensions.sh
  services/events/project/db/init.sql
  services/events/project/tests/test_config.py
  services/events/project/tests/test_event_model.py
  services/events/project/tests/test_speaker_model.py
  services/events/project/tests/test_video_model.py
  services/events/project/tests/utils.py
  services/users/project/db/Dockerfile
  services/users/project/db/extensions.sh
  services/users/project/db/init.sql
  test.sh
Labels: JavaScript, Python, SQL

#272 Fix for endpoint URIs and loading data
  docker-push.sh
  scripts/load_data.sh
Labels: Build, Shell Script, deployment
