Repository apoclyps/my-dev-space, pull requests merged in 2019-02, with the labels that each got.

#757 [no-ticket] Workshop fixes
  services/events/project/scripts/README.md
  services/events/project/scripts/event_tool.py
Labels: documentation

#758 footer overlay style fix
  services/client/src/components/footer/styles.js
Labels: CSS, bug, enhancement

#762 Adding Venezuela and Brighton to supported cities
  services/client/src/pages/events/components/events.js
Labels: javascript
